### PR TITLE
Caught access denied error to admin dashboard

### PR DESCRIPTION
**Pull request by Reaper45**
Catches the access denied error when a user is redirected to /admin after registration.

### CODE REVIEW

**Comment by microstudi** [comment]
Can you explain whay you want to do that?
i think throwing an exception will indicate why you are not allowed in this administration zone (Access Denied)

**Comment by Reaper45** [comment]
This is the error!
screenshot from 2017-06-14 17-48-03

**Comment by microstudi** [comment]
An your user is admin/superadmin? if not this is correct (the debuging lines are not shown in a production environtment).
Can you show me the result of this SQL query?:
`SELECT * FROM user_role WHERE user_id='ivan';`
Change the 'ivan' for your user id

**Comment by Reaper45** [comment]
The table `user_role` is empty.

**Comment by Reaper45** [comment]
My `user_id` is `joram`, and the record is not in the `user_role` table.

**Pull request closed without merging**
