### PR TITLE
Fix flow of invest when it fails and there is Invest Origin

### PR DESCRIPTION
**Pull request by davidbeig**

### CODE REVIEW

**Review by carlos-mg89 — DISMISSED** [review]

**Comment by javicarrillo** [comment]
It doesn't work for me, I've tested it with dummy method and I get a redirection to /donate .

Captura de pantalla de 2022-06-20 10-14-07

**Review by javicarrillo — CHANGES_REQUESTED** [review]
It needs to be review, the redirection is not working.

**Comment by davidbeig** [comment]
The code works, the only thing that it's meant to change the funcionality of the donation flow when there is a Invest origin, it does not change the behaviour for a normal donation.

**Comment by javicarrillo** [comment]
Ok, I understand now, thanks by the fix in the main donation flow related with invest origin, that was the error really.

**Review by javicarrillo — APPROVED** [review]

**Pull request merged**
